apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: asruf/order-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "yugabyte-ysql.yugabyte.svc.cluster.local"
            - name: DB_PORT
              value: "5433"
          limit: